#!/bin/bash
cd ~/Documents/LancsPC/MyRepos/dotfiles/
cp ~/.bashrc bashrc
cp ~/.vim/UltiSnips/r.snippets r.snippets
# sed -i '1i# ~/.vim/UltiSnips/r.snippets\' r.snippets
cp ~/.config/redshift.conf redshift.conf
cp /etc/R/Rprofile.site Rprofile.site
cp /etc/apt/sources.list sources.list
cp ~/.tmux.conf tmux.conf
cp ~/.unison/default.prf unison-default.prf
cp ~/.vimrc vimrc
